#!/usr/bin/env python3
"""Regenerate the TODO section of README.md from the dashboard TODO board.

The block between README_START and README_END in README.md is generated from
tools/dashboard/data/todo.json; everything else in README.md is hand-written.
It runs automatically: the dashboard server after every TODO change, the Claude Code
PostToolUse hook when todo.json is written, and .githooks/pre-commit as a backstop.

  python3 tools/readme_sync.py           rewrite the block (no-op when already current)
  python3 tools/readme_sync.py --check   exit 1 if README.md is out of date
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(ROOT, "README.md")
TODO = os.path.join(ROOT, "tools", "dashboard", "data", "todo.json")
START = "<!-- TODO:START (generated by tools/readme_sync.py from tools/dashboard/data/todo.json; edit the board, not this block) -->"
END = "<!-- TODO:END -->"
DONE_SHOWN = 10

SECTIONS = [
    ("doing", "In progress"),
    ("next", "Up next"),
    ("backlog", "Backlog (future work)"),
]


def one_line(text):
    return " ".join((text or "").split()).replace("|", "\\|")


def render(items):
    out = [START, ""]
    for status, heading in SECTIONS:
        rows = [i for i in items if i.get("status") == status]
        out.append(f"### {heading} ({len(rows)})")
        out.append("")
        if not rows:
            out.append("_Nothing here right now._")
        for i in rows:
            detail = one_line(i.get("detail"))
            out.append(f"- **{one_line(i['title'])}**" + (f": {detail}" if detail else ""))
        out.append("")
    done = sorted((i for i in items if i.get("status") == "done"), key=lambda i: i.get("done") or i.get("updated") or "", reverse=True)
    out.append(f"### Recently done ({len(done)})")
    out.append("")
    if not done:
        out.append("_Nothing finished yet._")
    for i in done[:DONE_SHOWN]:
        when = (i.get("done") or i.get("updated") or "")[:10]
        out.append(f"- ~~{one_line(i['title'])}~~" + (f" ({when})" if when else ""))
    out.append("")
    out.append(END)
    return "\n".join(out)


def build(readme_text):
    try:
        with open(TODO, encoding="utf-8") as f:
            items = json.load(f).get("items", [])
    except (OSError, ValueError):
        return readme_text
    block = render(items)
    a, b = readme_text.find(START), readme_text.find(END)
    if a == -1 or b == -1 or b < a:
        return readme_text.rstrip("\n") + "\n\n## TODO\n\n" + block + "\n"
    return readme_text[:a] + block + readme_text[b + len(END):]


def sync(check=False):
    """Returns True if README.md was (or, with check, would be) unchanged."""
    try:
        with open(README, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return True
    new = build(text)
    if new == text:
        return True
    if not check:
        with open(README, "w", encoding="utf-8") as f:
            f.write(new)
    return False


if __name__ == "__main__":
    if "--check" in sys.argv[1:]:
        if not sync(check=True):
            print("README.md TODO section is out of date: run python3 tools/readme_sync.py", file=sys.stderr)
            sys.exit(1)
    elif not sync():
        print("README.md TODO section updated from todo.json")
